### ISSUE TITLE
make prefix configurable, and allow no prefix

### ISSUE THREAD

**Issue by tacman** [zenstruck/twig-service-bundle#18]
Re: #17 

I'd prefer to make the twig calls without the fn_ prefix.  Or perhaps to prefix my application twig functions with app_, for example.

It's awkward to need the fn_, but since that's how it currently works, maybe you could make it configurable and default to fn_ , but allow none.

```php
    # injected into twig via
    #[AsTwigFunction('source_icon')] # fn_source_icon
    static public function getSourceIcon(string $source): ?string
```

```yaml
zenstruck_twig_service:
  functions:
    - iterator_to_array # available as "fn_iterator_to_array()" in twig
    - json_decode #fn_json_decode
    - file_exists
```

Could be 

```yaml
zenstruck_twig_service:
 prefix: false # or "" 
 functions:
    - iterator_to_array # available as "iterator_to_array()" in twig
    - json_decode # json_decode
    - file_exists
```
